export const ADD_ROUTE_POINT = "ADD_ROUTE_POINT";
export const REMOVE_ROUTE_POINT = "REMOVE_ROUTE_POINT";
export const MOVE_ROUTE_POINT = "MOVE_ROUTE_POINT";
export const REORDER_ROUTE_POINTS = "REORDER_ROUTE_POINTS";
